apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: josecarlosanpedrokubernetesreactjs 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: josecarlosanpedrokubernetesreactjs 
    spec:
      containers:
        - name: josecarlosanpedrokubernetesreactjs 
          image: josecarlosanpedro.azurecr.io/josecarlosanpedrokubernetesreactjs
          ports:
          - containerPort: 80