apiVersion : apps/v1
kind: Deployment
metadata:
  name: josecarlosanpedrokubernetesreactjs-deploy
  labels:
    name: josecarlosanpedrokubernetesreactjs-deploy
    app: josecarlosanpedrokubernetesreactjs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: josecarlosanpedrokubernetesreactjs-pod
      app: josecarlosanpedrokubernetesreactjs
  template:
    metadata:
      name: josecarlosanpedrokubernetesreactjs-pod
      labels:
        name: josecarlosanpedrokubernetesreactjs-pod
        app: josecarlosanpedrokubernetesreactjs
    spec:
      containers:
        - name: josecarlosanpedrokubernetesreactjs 
          image: josecarlosanpedro.azurecr.io/josecarlosanpedrokubernetesreactjs
          ports:
          - containerPort: 80